# Generated by Django 5.0.4 on 2024-04-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_num_dossier",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("client_num", models.CharField(max_length=500)),
                ("client_nom", models.CharField(max_length=500)),
                ("client_prenom", models.CharField(max_length=500)),
                (
                    "client_nom_prenom",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "client_prenom_nom",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "client_mail",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_telephone",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("1", "EXTERNE"), ("0", "INTERNE"), ("2", "AUTRE")],
                        default=2,
                        max_length=10,
                    ),
                ),
                ("client_datenaissance", models.DateField(blank=True, null=True)),
                (
                    "client_uuid",
                    models.CharField(
                        blank=True, max_length=600, null=True, unique=True
                    ),
                ),
                (
                    "client_code_postale",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_language",
                    models.CharField(default="Français", max_length=500),
                ),
                (
                    "client_commentaire",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("client_langue_res", models.CharField(default="", max_length=500)),
                ("client_commune", models.CharField(default="", max_length=500)),
                ("client_medref", models.CharField(default="", max_length=500)),
                ("client_cin", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "client_ville",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_adresse",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_profession",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_sexe",
                    models.CharField(
                        choices=[("1", "Homme"), ("0", "Femme"), ("2", "Non defini")],
                        default=2,
                        max_length=10,
                    ),
                ),
                (
                    "client_provenance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Facebook", "Facebook"),
                            ("Instagram", "Instagram"),
                            ("Tiktok", "Tiktok"),
                            ("Google", "Google"),
                            ("Recommandation patient", "Recommandation patient"),
                            ("Recommandation médecin", "Recommandation médecin"),
                        ],
                        default=None,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "client_id_externe",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_ref_mutuelle_externe",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_ref_compte_externe",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
    ]
