# Generated by Django 4.2.9 on 2024-04-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_calendarevent_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarevent",
            name="client",
        ),
    ]
