# Generated by Django 4.2.9 on 2024-05-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_calendarevent_created_at_calendarevent_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientmodel",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
    ]
